baseURL = "https://weivayn.github.io/thisiswei/"
URL = "thisiswei/posts"
title = "This is Wei"
copyright = "© 2017 thisiswei"
publishDir = "docs"
theme = "minimo"

disqusShortname = "thisiswei"
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
dateFormat = "Jan 02, 2006"
copyrightOwner = "thisiswei"
copyrightStartYear = "2017"
favicon = "favicon.ico"
hideEntryNavigation = false
#  customJS = ["js/custom.js"]
hideSocialMenu = false
showReadTime = true

[params.info]
  description = "Everything about Wei"
[params.settings]
  recentPostsLength = 5
[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"
[params.opengraph]
  [params.opengraph.facebook]
    admins = []
    appid = ""
[params.assets]
  customCss = ["css/custom.css"]

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Wei"

[params.social]
  email = "wei@thisiswei.com"
  github = "weivayn"
  instagram = "weivayn"
  twitter = "weivayn"
  linkedin = "weivayn"
  yelp = "thisiswei.yelp.com"

[params.social.config]
  platforms = ["github","twitter","instagram","email","linkedin","yelp"]

[permalinks]
  page = "/:slug/"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1

[blackfriday]
    plainIDAnchors = true
    hrefTargetBlank = true
